vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.swapfile = false

vim.lsp.enable({"lua_ls", "nixd", "tinymist"})

-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '{{colors.background.default.hex}}',
  base01 = '{{colors.surface_container_lowest.default.hex}}',
  base02 = '{{colors.surface_container_low.default.hex}}',
  base03 = '{{colors.outline_variant.default.hex}}',
  base04 = '{{colors.on_surface_variant.default.hex}}',
  base05 = '{{colors.on_surface.default.hex}}',
  base06 = '{{colors.inverse_on_surface.default.hex}}',
  base07 = '{{colors.surface_bright.default.hex}}',

  base08 = '{{colors.error.default.hex}}',
  base09 = '{{colors.tertiary.default.hex}}',
  base0A = '{{colors.secondary.default.hex}}',
  base0B = '{{colors.primary.default.hex}}',
  base0C = '{{colors.tertiary_container.default.hex}}',
  base0D = '{{colors.primary_container.default.hex}}',
  base0E = '{{colors.secondary_container.default.hex}}',
  base0F = '{{colors.error.default.hex}}',
})
-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

vim.api.nvim_set_hl(0, 'Visual', {
  bg = "{{colors.on_primary_container.default.hex}}",          
  fg = "{{colors.surface.default.hex}}",                       
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '{{colors.on_tertiary_container.default.hex}}',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '{{colors.tertiary.default.hex}}',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '{{colors.secondary.default.hex}}',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '{{colors.inverse_primary.default.hex}}',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '{{colors.surface_container_lowest.default.hex}}',
  fg = '{{colors.primary.default.hex}}',
})


vim.api.nvim_set_hl(0, 'Visual', {
  bg = "{{colors.on_primary_container.default.hex}}",          
  fg = "{{colors.surface.default.hex}}",                       
})

require('lualine').setup({
  options = {
    theme = "base16",
  }
})

local function source_matugen()
  local matugen_path = os.getenv("HOME") .. "/.config/nvim/generated.lua"

  local file, err = io.open(matugen_path, "r")
  if err ~= nil then
    vim.cmd('colorscheme base16-catppuccin-mocha')
    vim.print("A matugen style file was not found, but that's okay! The colorscheme will dynamically change if matugen runs!")
  else
    dofile(matugen_path)
    io.close(file)
  end
end

local function auxiliary_function()
  source_matugen()
  dofile(os.getenv("HOME") .. '/.config/nvim/config/plugins/lualine-nvim.lua')
  vim.api.nvim_set_hl(0, "Comment", { italic = true })
end

vim.api.nvim_create_autocmd("Signal", {
  pattern = "SIGUSR1",
  callback = auxiliary_function,
})
